languageCode = "en-us"
title = "HomePage"
baseurl = "http://example.org/"
theme = "aerial"

[params]
  name = "Arnau Colominas Illa"
  about = "SysAdmin &nbsp;&bull;&nbsp; Curious &nbsp;&bull;&nbsp;Mountains"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "false"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/acolominas"

[[params.social]]
  medium = "Linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/arnaucolominas/"

[[params.social]]
  medium = "Strava"
  icon = "rebel"
  link = "https://www.strava.com/athletes/15630465"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:acolominasilla@gmail.com"
